---
name: ci_read_job_execution_status_from_running_builds
description: |
  Determine a Runner/RunnerManager's job_execution_status by reading
  from ci_running_builds table instead of p_ci_builds.
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/598582
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/234123
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/598784
milestone: '19.0'
group: group::ci platform
type: gitlab_com_derisk
default_enabled: false
